# Voorbeeld configuraties voor Innodigi Thermostat Card

# Basis configuratie - minimale setup
type: custom:innodigi-thermostat-card
entity: climate.woonkamer

---

# Configuratie met aangepaste naam
type: custom:innodigi-thermostat-card
entity: climate.slaapkamer
name: Slaapkamer Thermostaat

---

# Dashboard voorbeeld - Meerdere thermostaten
views:
  - title: Verwarming
    path: verwarming
    cards:
      - type: custom:innodigi-thermostat-card
        entity: climate.woonkamer
        name: Woonkamer
      
      - type: custom:innodigi-thermostat-card
        entity: climate.slaapkamer
        name: Slaapkamer
      
      - type: custom:innodigi-thermostat-card
        entity: climate.studeerkamer
        name: Studeerkamer

---

# Grid layout voorbeeld
type: grid
columns: 2
cards:
  - type: custom:innodigi-thermostat-card
    entity: climate.woonkamer
    name: Woonkamer
  
  - type: custom:innodigi-thermostat-card
    entity: climate.slaapkamer
    name: Slaapkamer
  
  - type: custom:innodigi-thermostat-card
    entity: climate.badkamer
    name: Badkamer
  
  - type: custom:innodigi-thermostat-card
    entity: climate.studeerkamer
    name: Studeerkamer

---

# Generic Thermostat entity voorbeeld
# Voeg dit toe aan configuration.yaml om een generieke thermostaat te maken

climate:
  - platform: generic_thermostat
    name: Woonkamer
    heater: switch.verwarming_woonkamer
    target_sensor: sensor.temperatuur_woonkamer
    min_temp: 15
    max_temp: 25
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0.0
    min_cycle_duration:
      minutes: 5
    away_temp: 16
    precision: 0.5

